added a fix to default to qa when localhost or develop link
unfoldingWord/gateway-edit pull request #428
Opened 2023-04-28 00:32 UTC by mandolyte

# Describe what your pull request addresses

- [ ] when no parameter for QA or PROD is provide, let the default be QA if the url is localhost or if it has develop in the url

## Test Instructions

Using `localhost` or the `develop--` link with current code, then clear persisted settings
![image](https://user-images.githubusercontent.com/1289437/235022610-a2dd25aa-169d-4344-9588-89a879111b91.png)

Then refresh screen and after login appears, notice that settings point to 'git.door43.org'

Now with this change do the same thing and notice that it points to `qa.door43.org`

2023-04-28 02:28 UTC, PhotoNomad0 commented
@mandolyte Is there an issue for this?  Is not connected to any.  Also this is set to merge into develop branch, so localhost will not be changed when testing features related to the 2.0.0 release.

2023-04-28 12:12 UTC, PhotoNomad0 commented
> @mandolyte Is there an issue for this? Is not connected to any. Also this is set to merge into develop branch, so localhost will not be changed when testing features related to the 2.0.0 release.

@mandolyte For more clarity this fix should also be merged into `release-v2.0.0` branch and should add a check for url of `deploy-preview`.  Also need to investigate why this change broke cypress test.

2023-05-30 20:05 UTC, theNerd247 requested changes

2023-05-30 21:01 UTC, mandolyte commented
@theNerd247 Since I have stepped away, I think you should make the changes requested. Plus it would give you some  practice.

Note also that @PhotoNomad0 has also made some suggestions.

2023-06-05 12:17 UTC, Joel-C-Johnson approved these changes
LGTM

2023-06-05 12:19 UTC, PhotoNomad0 commented on src/context/AuthContext.js
> +    console.log('URL is:',window.location.href)
This is OK for run-time troubleshooting.

2023-06-05 12:19 UTC, PhotoNomad0 commented on src/components/Layout.js
> +      console.log('Server specified:',params.server)
This is OK for run-time troubleshooting.

2023-06-05 12:20 UTC, PhotoNomad0 commented on package.json
> +    "dev": "bash -c \"source ./scripts/set-env.sh && cross-env NODE_OPTIONS=--max_old_space_size=4096 next\"",
Yes it fixed problems building locally on PCs with only 16GB of RAM or less.

2023-06-05 13:38 UTC, Joel-C-Johnson approved these changes

2023-06-05 13:49 UTC, merged