Feature joel 452
unfoldingWord/gateway-edit pull request #494
Opened 2023-06-28 13:53 UTC by Joel-C-Johnson

# Describe what your pull request addresses

- [ ]

## Test Instructions

- [ ]

2023-06-29 15:20 UTC, PhotoNomad0 requested changes

2023-06-29 15:20 UTC, PhotoNomad0 commented on package.json
> +    "bible-reference-rcl": "1.2.1-beta.1",
Need to update this to 1.2.1

2023-07-03 12:41 UTC, Joel-C-Johnson commented on package.json
> +    "bible-reference-rcl": "1.2.1-beta.1",
sure

2023-07-03 13:06 UTC, Joel-C-Johnson reviewed
updated the Version number

2023-07-03 14:31 UTC, merged